### ISSUE TITLE
Multiple TV Sections found

### ISSUE THREAD

**Issue by fotomut** [hyperlink/plex-tv-cleanup#16]
What is the meaning of this error "Multiple TV sections found?"
How can I resolve this.
```
ℹ Dry Run
Error: Multiple TV sections found.
    at /usr/local/lib/node_modules/plex-tv-cleanup/index.js:55:11
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/plex-tv-cleanup/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by hyperlink** [comment]
Do you have more than one TV section in your plex library? This was originally designed for my use case of clean up one section.

**Comment by fotomut** [comment]
I guess I'm not sure what a "section" is in this domain. I do have two
things that I would call libraries I guess. Basically I created one library
that contains all the shows I would never want to delete and the other
library watches every other TV directory I have.

Based on this tool though, with it's ability to dnd a folder, maybe I
should rethink my strategy? I'm relatively new to the Plex world, having
managed things myself for years

**Comment by hyperlink** [comment]
Sure sections can be mapped to plex "libraries". 

Here's mine: 
![image](https://user-images.githubusercontent.com/133309/32970187-ee9212ca-cbb5-11e7-90d4-11bdaadf5302.png)

In my case I only have one type `tv` section/library but two of type `movie`. I will look into how to make it compatible with multiple TV sections.
